### PR TITLE
add pre and post hooks for customized reconcile logic

### PR DESCRIPTION
**Pull request by ryanzhang-oss**
- add extra status fields for customized reconcile
- add pre and post hooks for customized reconcile logic

### CODE REVIEW

**Comment by ryanzhang-oss** [comment]
> LGTM, can you help add a doc about how to use pre/post hooks?

yes, I will add tests cases to demonstrate how to use those hooks after EDAS sign off

**Comment by Diddaa** [comment]
Looks Great👍 ，i think we need support these requirements:
1. logger maxSize and maxBackup support;
2. postHook's failure break Render and Apply, but shouldn't break postHook;

**Comment by wonderflow** [comment]
This PR has already merged in [dev branch](https://github.com/crossplane/oam-kubernetes-runtime/tree/dev), let's use that for test and finally merge from that PR.

**Comment by Diddaa** [comment]
1. no way to add Hook before setup;
2. no way to own & index specific custom resource;
3. typo:  pkg/controller/v1alpha2/applicationconfiguration/controllrhooks.go
4. Withprehook/Withposthook throw  nil panic
5. for cluster installed v1alpha1 appconfig crd, error throwed when install v1alpha2

The CustomResourceDefinition "applicationconfigurations.core.oam.dev" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions

**Comment by Diddaa** [comment]
LGTM

**Pull request merged**
