### PR TITLE
feat: add debug-flag for enabling logs

### LINKED ISSUE #284: [Feature] make development log setting as an argument
image

Currently the development flag is always true, so we will get lot's of debug log by default.

I think we should make the default development flag to be false, and add a command in Makefile such as `make debug-run` to switch the flag on.

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>

fixes #284

### CODE REVIEW

**Comment by kushthedude** [comment]
Hi team, I am not sure if lint-failure is due to the changes in the PR?

**Comment by resouer** [comment]
@kushthedude Seems not, it should be OK after re-run.

**Review by wonderflow — APPROVED** [review]
Good job!

**Comment by wonderflow** [comment]
@kushthedude Would you like to fix the same issue in KubeVela https://github.com/oam-dev/kubevela/blob/master/cmd/core/main.go#L120

**Comment by kushthedude** [comment]
Sur @wonderflow !

**Pull request merged**
